### ISSUE TITLE
Add Trino-datasource in Grafana has error "this.getRef is not a function"

### ISSUE THREAD

**Issue by zjeoff** [starburstdata/grafana-trino#39]
when i use this new plugin as your post here (https://github.com/starburstdata/grafana-trino/releases/download/v1.0.0-beta.1/trino-datasource.zip), i got a error when add a trino-datasource.

the error is : "this.getRef is not a function"

see the error picture as i attached.
![image](https://user-images.githubusercontent.com/25643034/169844567-11acb94d-0aae-4989-873d-e5ef7157586c.png)

Grafana version: 8.2.4

Look forward to your help...

**Comment by nineinchnick** [comment]
Indeed Grafana 8.2 is missing [the DataSourceApi.getRef](https://grafana.com/docs/grafana/latest/packages_api/data/datasourceapi/#getref-method) method: https://grafana.com/docs/grafana/v8.2/packages_api/data/datasourceapi/

I'll try to see what was used before, but in the meantime, can you upgrade to a newer version?

**Comment by zjeoff** [comment]
@nineinchnick  thanks for the update. yeah. after upgrading to 8.5, the issue has been fixed. thanks.
